export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const POST_STATUS_LOADING = 'POST_STATUS_LOADING' 
export const POST_STATUS_SUCCESS = 'POST_STATUS_SUCCESS' 
export const POST_STATUS_FAIL = 'POST_STATUS_FAIL' 

export const UPDATE_STATUS_LOADING = 'UPDATE_STATUS_LOADING' 
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS' 
export const UPDATE_STATUS_FAIL = 'UPDATE_STATUS_FAIL' 

export const DELETE_TWEET_LOADING = 'DELETE_TWEET_LOADING' 
export const DELETE_TWEET_SUCCESS = 'DELETE_TWEET_SUCCESS' 
export const DELETE_TWEET_FAIL = 'DELETE_TWEET_FAIL' 

export const FIND_ALL_STATUS_LOADING = 'FIND_ALL_STATUS_LOADING' 
export const FIND_ALL_STATUS_SUCCESS = 'FIND_ALL_STATUS_SUCCESS' 
export const FIND_ALL_STATUS_FAIL = 'FIND_ALL_STATUS_FAIL' 

export const FIND_ONE_STATUS_LOADING = 'FIND_ONE_STATUS_LOADING' 
export const FIND_ONE_STATUS_SUCCESS = 'FIND_ONE_STATUS_SUCCESS' 
export const FIND_ONE_STATUS_FAIL = 'FIND_ONE_STATUS_FAIL' 

export const DELETE_STATUS_LOADING = 'DELETE_STATUS_LOADING' 
export const DELETE_STATUS_SUCCESS = 'DELETE_STATUS_SUCCESS' 
export const DELETE_STATUS_FAIL = 'DELETE_STATUS_FAIL' 

export const GET_MESSAGE = 'GET_MESSAGE' 
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE' 
export const ADD_NEW_CONVERSATION = 'ADD_NEW_CONVERSATION' 
